# pr001.yml

rhbase_install_packages:
  - dhcp

rhbase_firewall_allow_services:
  - dhcp

dhcp_global_domain_name_servers:
  - 192.0.2.10
  - 192.0.2.11

dhcp_global_default_lease_time: 43200

dhcp_global_domain_name: avalon.lan

dhcp_global_routers: 172.16.255.254

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    domain_name_servers: 172.16.255.254
    default_lease_time: 43200
    pools:
      - allow: unknown-clients
        default_lease_time: 43200
        domain_name_servers: 172.16.255.254
        range_begin: 172.16.192.1
        range_end: 172.16.255.253
      - allow: known-clients
        domain_name_servers: 172.16.255.254
        range_begin: 172.16.128.1
        range_end: 172.16.191.254

dhcp_hosts:
  - name: werkstation
    mac: '08:00:27:70:9B:E5'
    ip: 172.16.128.2
