# puOO4.yml

rhbase_firewall_allow_services:
    - http
    - https

mariadb_databases:
  - name: wordpressdb

mariadb_users:
  - name: ebutinastepe
    password: M@ria
    priv: '*.*:ALL,GRANT'

mariadb_root_password: M@riaRoot

wordpress_database: wordpressdb
wordpress_user: ebutinastepe
wordpress_password: M@ria

#Certificaten
httpd_SSLCertificateFile: /etc/pki/tls/certs/ca.crt
httpd_SSLCertificateKeyFile: /etc/pki/tls/private/ca.key