# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_motd: true
rhbase_repositories:
  - epel-release
rhbase_install_packages:
  - bash-completion
  - bind-utils
  - vim-enhanced
  - git
  - nano
  - tree
  - wget
rhbase_firewall_allow_services:
  - http
  - https
rhbase_admin_user: ebu
rhbase_admin_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPfUrrv3mde/PyDRPyCau61frmoqK//fEIW3E/mK/6iw5Hmvb6YVfqf6dKC7cPX1ksl6Mc7JiWGJfZW7ZOCq6PirGfiUiyE6lxRNuZ8xQLmPzRj5hFkqt7lqoLVGh5ldds3BMv4PRsVY2t02kjKljmqCKwk999z7yJ0mvqr922/yv28Ikt+b5CwPa4Pud/pK+Hno24rF4kAWQcYywjl5Mqmx795wy32DgeTASWy0o1VbimnWQMjsB3595eOAT9InGFEL9mNYKnVWzOKSUfmNW7KiTvtyCk0F+F91fuXID04DDfEo9C8EW5TqLAzX6VEbLeKJBSo41vcQiXSu2AvKMj ebuti@EBU-BEKIR

rhbase_users:
  - name: ebu
    comment: 'Ebu Bekir Tinastepe'
    password: $6$DDjLVsvX0vW7hFmr$RWQ5BeChdYcEefCJvhdXo53qPfKK/3lVhH7S4R67jgI5TxLULfjnTqt9Imd30YyiOdpomoCU9qg6VQgfcI.Lc0
    groups:
      - users
      - wheel
