# site.yml
---
- hosts: pu004
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
  pre_tasks:
    - name: Webserver private key kopieren
      copy:
        src: file-cert/pu004.key
        dest: /etc/pki/tls/private/ca.key
    - name: Web server certificaat kopieren
      copy:
        src: file-cert/pu004.crt
        dest: /etc/pki/tls/certs/ca.crt
- hosts: pu001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind
- hosts: pu002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind
- hosts: pr011
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd
